### ISSUE TITLE
Weekday and DayOfMonth methods should wait when the day provided is today

### ISSUE THREAD

**Issue by mKurrels** [zenaton/zenaton-ruby#46]
### Expected Behavior:
per the discussion with @geomagilles:

if we are on Monday, 11am on the 23rd of the month. Then:

.Monday(1) should wait until next Monday at 11am
.Monday(1).At("9") should wait until next Monday at 9am
.Monday(1).At("13") should wait 2 hours only
.DayOfMonth(23) should wait for one month
.DayOfMonth(23).At("13") should wait for only 2 hours

### Problem:
Currently, if today is a Monday, when calling `Zenaton::Tasks::Wait.new.monday` you don't actually wait until the next Monday, and the wait terminates immediately. 

We have the same issue with the `dayOfMonth` method. If it's the 23rd and you call `Zenaton::Tasks::Wait.new.day_of_month(23)` you won't wait until the next month, but instead the wait will terminate immediately.

Specifically, I believe the two problematic lines are these: 
https://github.com/zenaton/zenaton-ruby/blob/5c19799915859d7b9e534b41d8e7059f73787578/lib/zenaton/traits/with_timestamp.rb#L102
https://github.com/zenaton/zenaton-ruby/blob/5c19799915859d7b9e534b41d8e7059f73787578/lib/zenaton/traits/with_timestamp.rb#L69

(note: I don't actually understand the ruby in the second link here, so I cannot confirm if the ruby library has the problem with weekdays that the other libraries do)

### Fix:
See https://github.com/zenaton/zenaton-go/pull/7 for the fix in the go library.

**Comment by idabmat** [comment]
Cheers @mKurrels for the thorough report. It was simple enough to write failing specs with the scenarios you described.

Tackling this now.
